name: Django Demo
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
  
      - name: Build Docker Image
        run: docker build -t app:test .
  
      - name: Run tests in Docker
        run: docker run app:test pytest
  
      - name: Check for missing migrations
        run: docker run app:test python manage.py makemigrations --check --dry-run 
